In [2]:
import mysql.connector
import pandas as pd

conn = mysql.connector.connect(
    host="18.136.157.135",
    port=3306,
    user="dm_team4",
    password="DM!$!Team!47@4!23&",
    database="project_medical_data_history"
)

print("Connected successfully!")

Connected successfully!

In [3]:
q1 = """
SELECT first_name, last_name, gender
FROM patients
WHERE gender = 'M';
"""

df1 = pd.read_sql(q1, conn)
df1

C:\Users\user\AppData\Local\Temp\ipykernel_16088\2797051699.py:7: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df1 = pd.read_sql(q1, conn)

     first_name   last_name gender
0        Donald  Waterfield      M
1        Mickey      Baasha      M
2          Jiji      Sharma      M
3         Blair        Diaz      M
4       Charles       Wolfe      M
...         ...         ...    ...
2463      Eddie       Drake      M
2464     Morgan     McCrary      M
2465        Sam       OHara      M
2466    Charlie     Neutron      M
2467    Armando    Matthews      M

[2468 rows x 3 columns]

In [4]:
q2 = """
SELECT first_name, last_name
FROM patients
WHERE allergies IS NULL;
"""

df2 = pd.read_sql(q2, conn)
df2

C:\Users\user\AppData\Local\Temp\ipykernel_16088\138783342.py:7: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df2 = pd.read_sql(q2, conn)

     first_name   last_name
0        Donald  Waterfield
1         Blair        Diaz
2        Thomas      ONeill
3         Sonny     Beckett
4        Cedric    Coltrane
...         ...         ...
2054         Bo       Darby
2055     Morgan     McCrary
2056        Sam       OHara
2057    Charlie     Neutron
2058      Fleur     Morales

[2059 rows x 2 columns]

In [5]:
q3 = """
SELECT first_name
FROM patients
WHERE first_name LIKE 'C%';
"""

df3 = pd.read_sql(q3, conn)
df3

C:\Users\user\AppData\Local\Temp\ipykernel_16088\1854745864.py:7: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df3 = pd.read_sql(q3, conn)

     first_name
0       Charles
1        Cedric
2       Charles
3         Cross
4      Calleigh
..          ...
297    Cordelia
298  Constantin
299     Charlie
300   Christine
301   Constance

[302 rows x 1 columns]

In [6]:
q4 = """
SELECT first_name, last_name
FROM patients
WHERE weight BETWEEN 100 AND 120;
"""

df4 = pd.read_sql(q4, conn)
df4

C:\Users\user\AppData\Local\Temp\ipykernel_16088\457872587.py:7: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df4 = pd.read_sql(q4, conn)

    first_name  last_name
0         Jiji     Sharma
1        Blair       Diaz
2       Thomas     ONeill
3        Sonny    Beckett
4          Tom  Halliwell
..         ...        ...
947       Todd     Dallas
948         Bo      Darby
949   Domenica     Ashton
950    Charlie    Neutron
951      Fleur    Morales

[952 rows x 2 columns]

In [9]:
q5 = """
SELECT patient_id, first_name, last_name,
       IFNULL(allergies, 'NKA') AS allergies
FROM patients;
"""

df5 = pd.read_sql(q5, conn)
df5

C:\Users\user\AppData\Local\Temp\ipykernel_16088\1015635540.py:7: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df5 = pd.read_sql(q5, conn)

      patient_id first_name   last_name   allergies
0              1     Donald  Waterfield         NKA
1              2     Mickey      Baasha       Sulfa
2              3       Jiji      Sharma  Penicillin
3              4      Blair        Diaz         NKA
4              5    Charles       Wolfe  Penicillin
...          ...        ...         ...         ...
4525        4526    Armando    Matthews  Penicillin
4526        4527      Karen    Costello  Penicillin
4527        4528     Deanna      Barnes  Penicillin
4528        4529      Molly     Hanover        Milk
4529        4530  Constance        Yang  Penicillin

[4530 rows x 4 columns]

In [10]:
q6 = """
SELECT CONCAT(first_name, ' ', last_name) AS full_name
FROM patients;
"""

df6 = pd.read_sql(q6, conn)
df6

C:\Users\user\AppData\Local\Temp\ipykernel_16088\450291144.py:6: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df6 = pd.read_sql(q6, conn)

              full_name
0     Donald Waterfield
1         Mickey Baasha
2           Jiji Sharma
3            Blair Diaz
4         Charles Wolfe
...                 ...
4525   Armando Matthews
4526     Karen Costello
4527      Deanna Barnes
4528      Molly Hanover
4529     Constance Yang

[4530 rows x 1 columns]

In [11]:
q7 = """
SELECT p.first_name,
       p.last_name,
       pr.province_name
FROM patients p
JOIN province_names pr
ON p.province_id = pr.province_id;
"""

df7 = pd.read_sql(q7, conn)
df7

C:\Users\user\AppData\Local\Temp\ipykernel_16088\3718958574.py:10: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df7 = pd.read_sql(q7, conn)

     first_name   last_name province_name
0        Donald  Waterfield       Ontario
1        Mickey      Baasha       Ontario
2          Jiji      Sharma       Ontario
3         Blair        Diaz       Ontario
4       Charles       Wolfe       Ontario
...         ...         ...           ...
4525    Armando    Matthews       Ontario
4526      Karen    Costello       Ontario
4527     Deanna      Barnes       Ontario
4528      Molly     Hanover       Ontario
4529  Constance        Yang       Ontario

[4530 rows x 3 columns]

In [12]:
q8 = """
SELECT COUNT(*) AS total_2010_births
FROM patients
WHERE YEAR(birth_date) = 2010;
"""

df8 = pd.read_sql(q8, conn)
df8

C:\Users\user\AppData\Local\Temp\ipykernel_16088\4279275962.py:7: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df8 = pd.read_sql(q8, conn)

   total_2010_births
0                 55

In [13]:
q9 = """
SELECT first_name, last_name, height
FROM patients
WHERE height = (SELECT MAX(height) FROM patients);
"""

df9 = pd.read_sql(q9, conn)
df9

C:\Users\user\AppData\Local\Temp\ipykernel_16088\3806390290.py:7: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df9 = pd.read_sql(q9, conn)

  first_name last_name  height
0        Sam    Haruko   226.0

In [14]:
q10 = """
SELECT *
FROM patients
WHERE patient_id IN (1, 45, 534, 879, 1000);
"""

df10 = pd.read_sql(q10, conn)
df10

C:\Users\user\AppData\Local\Temp\ipykernel_16088\65211932.py:7: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df10 = pd.read_sql(q10, conn)

,patient_id,first_name,last_name,gender,birth_date,city,province_id,allergies,height,weight
0,1,Donald,Waterfield,M,1963-02-12,Barrie,ON,NaN,156.0,65.0
1,45,Cross,Gordon,M,2009-03-20,Ancaster,ON,NaN,125.0,53.0
2,534,Don,Zatara,M,2008-01-11,Timmins,ON,NaN,136.0,67.0
3,879,Orla,Shawn,F,1967-09-24,Sarnia,ON,Penicillin,149.0,65.0
4,1000,Rick,Williams,M,1975-04-13,Hamilton,ON,Penicillin,176.0,127.0

In [15]:
q11 = """
SELECT COUNT(*) AS total_admissions
FROM admissions;
"""

df11 = pd.read_sql(q11, conn)
df11

C:\Users\user\AppData\Local\Temp\ipykernel_16088\3165257623.py:6: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df11 = pd.read_sql(q11, conn)

   total_admissions
0              5067

In [16]:
q12 = """
SELECT *
FROM admissions
WHERE admission_date = discharge_date;
"""

df12 = pd.read_sql(q12, conn)
df12

C:\Users\user\AppData\Local\Temp\ipykernel_16088\2014529533.py:7: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df12 = pd.read_sql(q12, conn)

,patient_id,admission_date,discharge_date,diagnosis,attending_doctor_id
0,1,2018-09-20,2018-09-20,Ineffective Breathin Pattern R/T Fluid Accumul...,24
1,9,2018-12-31,2018-12-31,Ruptured Appendicitis,19
2,10,2019-02-27,2019-02-27,Lower Quadrant Pain,27
3,17,2019-03-04,2019-03-04,Diabetes Mellitus,9
4,28,2019-03-30,2019-03-30,Cancer Of The Stomach,26
...,...,...,...,...,...
476,4483,2019-02-19,2019-02-19,Congestive Heart Failure,16
477,4494,2019-03-07,2019-03-07,Repair Stab Wound,27
478,4501,2018-07-09,2018-07-09,C-Section Delivery Day 4,27
479,4511,2019-03-11,2019-03-11,Prostatectomy,25
480,4512,2018-10-02,2018-10-02,Fibromyalgia,10

In [17]:
q13 = """
SELECT COUNT(*) AS total_admissions_579
FROM admissions
WHERE patient_id = 579;
"""

df13 = pd.read_sql(q13, conn)
df13

C:\Users\user\AppData\Local\Temp\ipykernel_16088\3225148671.py:7: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df13 = pd.read_sql(q13, conn)

   total_admissions_579
0                     2

In [18]:
q14 = """
SELECT DISTINCT city
FROM patients
WHERE province_id = 'NS';
"""

df14 = pd.read_sql(q14, conn)
df14

C:\Users\user\AppData\Local\Temp\ipykernel_16088\4132782942.py:7: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df14 = pd.read_sql(q14, conn)

              city
0  Port Hawkesbury
1          Halifax
2        Inverness

In [21]:
q15 = """
SELECT first_name, last_name, birth_date
FROM patients
WHERE height > 160
AND weight > 70;
"""

df15 = pd.read_sql(q15, conn)
df15

C:\Users\user\AppData\Local\Temp\ipykernel_16088\2616593381.py:8: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df15 = pd.read_sql(q15, conn)

     first_name last_name  birth_date
0        Mickey    Baasha  1981-05-28
1          Jiji    Sharma  1957-09-05
2         Blair      Diaz  1967-01-07
3        Thomas    ONeill  1993-01-31
4         Sonny   Beckett  1952-12-11
...         ...       ...         ...
2086      Fleur   Morales  1992-03-02
2087    Armando  Matthews  1987-12-20
2088     Deanna    Barnes  1983-04-05
2089      Molly   Hanover  1999-10-23
2090  Constance      Yang  2002-07-17

[2091 rows x 3 columns]

In [2]:
q16 = """
SELECT DISTINCT YEAR(birth_date) AS birth_year
FROM patients
ORDER BY birth_year ASC;
"""

df16 = pd.read_sql(q16, conn)
df16

C:\Users\user\AppData\Local\Temp\ipykernel_3464\2524673908.py:7: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df16 = pd.read_sql(q16, conn)

    birth_year
0         1918
1         1923
2         1925
3         1926
4         1927
..         ...
88        2014
89        2015
90        2016
91        2017
92        2018

[93 rows x 1 columns]

In [3]:
q17 = """
SELECT first_name
FROM patients
GROUP BY first_name
HAVING COUNT(first_name) = 1;
"""

df17 = pd.read_sql(q17, conn)
df17

C:\Users\user\AppData\Local\Temp\ipykernel_3464\3693272055.py:8: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df17 = pd.read_sql(q17, conn)

    first_name
0         Abby
1     Adelaide
2       Adelia
3        Akira
4       Albert
..         ...
314    Zachary
315       Zack
316        Zen
317       Ziva
318        Zoe

[319 rows x 1 columns]

In [4]:
q18 = """
SELECT patient_id, first_name
FROM patients
WHERE first_name LIKE 's%s'
AND LENGTH(first_name) >= 6;
"""

df18 = pd.read_sql(q18, conn)
df18

C:\Users\user\AppData\Local\Temp\ipykernel_3464\824797359.py:8: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df18 = pd.read_sql(q18, conn)

    patient_id  first_name
0          496      Spiros
1          629      Spiros
2          648  Stanislaus
3         1273  Stanislaus
4         1789      Seamus
5         1926  Stanislaus
6         1996  Stanislaus
7         2258      Spiros
8         2378  Stanislaus
9         2771  Stanislaus
10        3487  Stanislaus

In [5]:
q19 = """
SELECT p.patient_id,
       p.first_name,
       p.last_name
FROM patients p
JOIN admissions a
ON p.patient_id = a.patient_id
WHERE a.diagnosis = 'Dementia';
"""

df19 = pd.read_sql(q19, conn)
df19

C:\Users\user\AppData\Local\Temp\ipykernel_3464\4217961821.py:11: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df19 = pd.read_sql(q19, conn)

    patient_id first_name   last_name
0          160    Miranda    Delacour
1          178      David  Bustamonte
2          207       Matt      Celine
3          613       Jaki     Granger
4          836    Montana       Vimes
5          924      Simon    Spellman
6         1201      Irene      Murphy
7         1264    Jillian   Valentine
8         1402    Kathryn      Hallow
9         1491      Doris      McGrew
10        1585       Alex   Cantropus
11        1749  Alejandro      Mellie
12        1798     Sister     Trenton
13        1844       Jadu      Wilson
14        1938    Anthony      Anneke
15        2292    Jessica      Talbot
16        2532       Lynn     Willing
17        2689       Kurt       Jones
18        2834     Juliet    Harkness
19        3375      Agnes     Barkley
20        3496      Harry       Lucas
21        3555       Jack      Caspar
22        3842    Claudia        Drew
23        4256       Rita       Wolfe
24        4357       Alex        Moss
25        4401   Mary Ann        Wali

In [6]:
q20 = """
SELECT first_name
FROM patients
ORDER BY LENGTH(first_name), first_name ASC;
"""

df20 = pd.read_sql(q20, conn)
df20

C:\Users\user\AppData\Local\Temp\ipykernel_3464\1632810617.py:7: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df20 = pd.read_sql(q20, conn)

         first_name
0                Al
1                Al
2                Al
3                Al
4                Al
...             ...
4525    Christopher
4526    Cresentmoon
4527    Cresentmoon
4528  Jean-Baptiste
4529  Jean-Baptiste

[4530 rows x 1 columns]

In [7]:
q21 = """
SELECT 
    SUM(CASE WHEN gender = 'M' THEN 1 ELSE 0 END) AS total_males,
    SUM(CASE WHEN gender = 'F' THEN 1 ELSE 0 END) AS total_females
FROM patients;
"""

df21 = pd.read_sql(q21, conn)
df21

C:\Users\user\AppData\Local\Temp\ipykernel_3464\1403580982.py:8: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df21 = pd.read_sql(q21, conn)

   total_males  total_females
0       2468.0         2062.0

In [8]:
q23 = """
SELECT patient_id, diagnosis, COUNT(*) AS admission_count
FROM admissions
GROUP BY patient_id, diagnosis
HAVING COUNT(*) > 1;
"""

df23 = pd.read_sql(q23, conn)
df23

C:\Users\user\AppData\Local\Temp\ipykernel_3464\2871981273.py:8: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df23 = pd.read_sql(q23, conn)

    patient_id                          diagnosis  admission_count
0          137                          Pregnancy                2
1          320                          Pneumonia                2
2         1577           Congestive Heart Failure                2
3         2004  Left Shoulder Rotator Cuff Repair                2
4         2859                Severed Spine At C3                2
5         3012                       Appendicitis                2
6         3367                     Pyelonephritis                2
7         3468           Congestive Heart Failure                2
8         4083           Congestive Heart Failure                2
9         4121           Congestive Heart Failure                2
10        4363           Congestive Heart Failure                2

In [9]:
q24 = """
SELECT city, COUNT(*) AS total_patients
FROM patients
GROUP BY city
ORDER BY total_patients DESC, city ASC;
"""

df24 = pd.read_sql(q24, conn)
df24

C:\Users\user\AppData\Local\Temp\ipykernel_3464\3585408664.py:8: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df24 = pd.read_sql(q24, conn)

          city  total_patients
0     Hamilton            1938
1      Toronto             317
2   Burlington             276
3    Brantford             147
4     Ancaster             117
..         ...             ...
88   Tuscorora               2
89  Unionville               2
90      Linton               1
91    Rockford               1
92  Ureterburg               1

[93 rows x 2 columns]

In [12]:
q25 = """
SELECT first_name, last_name, 'Patient' AS role
FROM patients

UNION

SELECT first_name, last_name, 'Doctor' AS role
FROM doctors;
"""

df25 = pd.read_sql(q25, conn)
df25

C:\Users\user\AppData\Local\Temp\ipykernel_3464\4240003149.py:11: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df25 = pd.read_sql(q25, conn)

     first_name   last_name     role
0        Donald  Waterfield  Patient
1        Mickey      Baasha  Patient
2          Jiji      Sharma  Patient
3         Blair        Diaz  Patient
4       Charles       Wolfe  Patient
...         ...         ...      ...
4533    Heather        Beck   Doctor
4534      Jenny     Pulaski   Doctor
4535   Jeanette       Sites   Doctor
4536      Larry      Miller   Doctor
4537      Donna   Greenwood   Doctor

[4538 rows x 3 columns]

In [14]:
q26 = """
SELECT allergies, COUNT(*) AS total
FROM patients
WHERE allergies IS NOT NULL
GROUP BY allergies
ORDER BY total DESC;
"""

df26 = pd.read_sql(q26, conn)
df26

C:\Users\user\AppData\Local\Temp\ipykernel_3464\514687579.py:9: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df26 = pd.read_sql(q26, conn)

              allergies  total
0            Penicillin   1082
1               Codeine    305
2                 Sulfa    157
3                   ASA     99
4           Sulfa Drugs     71
..                  ...    ...
58               Gluten      2
59              Demerol      1
60             Sulphate      1
61                 Dust      1
62  Sulfa Surgical Tape      1

[63 rows x 2 columns]

In [15]:
q27 = """
SELECT first_name, last_name, birth_date
FROM patients
WHERE birth_date BETWEEN '1970-01-01' AND '1979-12-31'
ORDER BY birth_date ASC;
"""

df27 = pd.read_sql(q27, conn)
df27

C:\Users\user\AppData\Local\Temp\ipykernel_3464\3114444949.py:8: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df27 = pd.read_sql(q27, conn)

        first_name   last_name  birth_date
0          Frances  Kobayakawa  1970-01-02
1            Sunny     Burrell  1970-01-07
2         Penelope     Beckett  1970-01-14
3          Deborah     Stewart  1970-01-14
4          Augusta      Decker  1970-01-22
..             ...         ...         ...
618          Dante       McKay  1979-12-04
619      Celestina  De Lesseps  1979-12-11
620  Jean-Baptiste        Bass  1979-12-12
621        Stephen     Summers  1979-12-29
622        Bolivar      Sawyer  1979-12-29

[623 rows x 3 columns]

In [16]:
q28 = """
SELECT CONCAT(UPPER(last_name), ',', LOWER(first_name)) AS full_name
FROM patients
ORDER BY first_name DESC;
"""

df28 = pd.read_sql(q28, conn)
df28

C:\Users\user\AppData\Local\Temp\ipykernel_3464\408208848.py:7: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df28 = pd.read_sql(q28, conn)

                full_name
0              MILLER,zoe
1             CORBIE,ziva
2     KOBAYAKAWA,zenigata
3     OVERSTREET,zenigata
4             BENNETT,zen
...                   ...
4525      LITTLEFIELD,abe
4526         HAMILTON,abe
4527            OGAWA,abe
4528             LUCA,abe
4529         KENDALL,abby

[4530 rows x 1 columns]

In [17]:
q29 = """
SELECT province_id, SUM(height) AS total_height
FROM patients
GROUP BY province_id
HAVING SUM(height) >= 7000;
"""

df29 = pd.read_sql(q29, conn)
df29

C:\Users\user\AppData\Local\Temp\ipykernel_3464\3079608081.py:8: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df29 = pd.read_sql(q29, conn)

  province_id  total_height
0          BC        7720.0
1          NS        9765.0
2          ON      678037.0

In [3]:
q30 = """
SELECT MAX(weight) - MIN(weight) AS weight_difference
FROM patients
WHERE last_name = 'Maroni';
"""

df30 = pd.read_sql(q30, conn)
df30

C:\Users\user\AppData\Local\Temp\ipykernel_20960\3278478181.py:7: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df30 = pd.read_sql(q30, conn)

   weight_difference
0               71.0

In [4]:
q31 = """
SELECT DAY(admission_date) AS day_of_month,
       COUNT(*) AS total_admissions
FROM admissions
GROUP BY DAY(admission_date)
ORDER BY total_admissions DESC;
"""

df31 = pd.read_sql(q31, conn)
df31

C:\Users\user\AppData\Local\Temp\ipykernel_20960\2296640715.py:9: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df31 = pd.read_sql(q31, conn)

    day_of_month  total_admissions
0             11               184
1              4               184
2              9               183
3              2               180
4             12               179
5              6               179
6             16               177
7             21               174
8             28               173
9             13               173
10             7               167
11             8               166
12            18               166
13             3               166
14            30               165
15            20               165
16            15               164
17            14               164
18            10               164
19             5               161
20            24               161
21            17               160
22            25               159
23            26               157
24             1               156
25            23               156
26            19               152
27            27               149
28            29               140
29            22               140
30            31               103

In [5]:
q32 = """
SELECT FLOOR(weight/10)*10 AS weight_group,
       COUNT(*) AS total_patients
FROM patients
GROUP BY weight_group
ORDER BY weight_group DESC;
"""

df32 = pd.read_sql(q32, conn)
df32

C:\Users\user\AppData\Local\Temp\ipykernel_20960\1656438372.py:9: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df32 = pd.read_sql(q32, conn)

    weight_group  total_patients
0            140               6
1            130              59
2            120             191
3            110             426
4            100             507
5             90             403
6             80             478
7             70             633
8             60             685
9             50             443
10            40             202
11            30             126
12            20             165
13            10             114
14             0              92

In [6]:
q33 = """
SELECT patient_id,
       weight,
       height,
       CASE 
           WHEN weight / POWER(height/100, 2) >= 30 THEN 1
           ELSE 0
       END AS isObese
FROM patients;
"""

df33 = pd.read_sql(q33, conn)
df33

C:\Users\user\AppData\Local\Temp\ipykernel_20960\4182665043.py:12: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df33 = pd.read_sql(q33, conn)

      patient_id  weight  height  isObese
0              1    65.0   156.0        0
1              2    76.0   185.0        0
2              3   106.0   194.0        0
3              4   104.0   191.0        0
4              5    10.0    47.0        1
...          ...     ...     ...      ...
4525        4526    74.0   173.0        0
4526        4527    22.0    75.0        1
4527        4528    73.0   161.0        0
4528        4529    91.0   167.0        1
4529        4530    71.0   177.0        0

[4530 rows x 4 columns]

In [8]:
q34 = """
SELECT p.patient_id,
       p.first_name,
       p.last_name,
       d.specialty
FROM patients p
JOIN admissions a
ON p.patient_id = a.patient_id
JOIN doctors d
ON a.attending_doctor_id = d.doctor_id
WHERE a.diagnosis = 'Epilepsy'
AND d.first_name = 'Lisa';
"""

df34 = pd.read_sql(q34, conn)
df34

C:\Users\user\AppData\Local\Temp\ipykernel_20960\3715482738.py:15: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df34 = pd.read_sql(q34, conn)

   patient_id first_name last_name                  specialty
0         468      Frank  Anderson  Obstetrician/Gynecologist
1         701   Precious    Ashton  Obstetrician/Gynecologist